### ISSUE TITLE
Need a way to specify the run period on the command line

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-fortran#30]
It would be useful to be able to specify the run period on the command line, which would override the control file.  Otherwise, you have to edit the control file.

**Comment by smalers** [comment]
Or, does it make sense to allow specifying an alternate `ctl` file on the command line?  Then you could change more than one configuration value or programatically modify the second file and use it with everything else in the dataset remaining the same.  I have created a "run" script that runs StateMod and want to be able to set the period to run, without impacting the core data files.  Can either modify a temporary `ctl` file and run with that, or specify StateMod command line options for the run period.

**Comment by smalers** [comment]
I added command line options to gfortran version and made other updates as follows (did not make changes to Lahey `parse` but might circle around, it is difficult to write that code without the compiler).

1. Now can specify `-iystr Year` and `-iyend Year` on the command line, which will override the values in the `ctl` file.  This allows tests to be run efficiently without having many copies of the control file.
2. Clarified how default startup log file `statem.log` and dataset log file are handled, made sure that log file `.log` cannot be created.
3. Prompt for response file name if not given rather than default to `statem` since most often users just forget to specify.  This functionality seems to have worked in the past but was broken.
4. Command line options, including response file name, can now be in any order. 
5. Split `getctl.for` code out of `datinp.for`.

I'm going to close this issue.  The functionality will be used in automated testing.

**Comment by Rayrbennett** [comment]
Steve see > Rrb below. 
Also breaking Lahey for silly stuff is, in my opinion a mistake.
