### ISSUE TITLE
execut.for has compile errors

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-fortran#35]
I've been copying Ray's 16.00.47 code into the workspace and updating the code to add GPL v3 notice.  The `execut.for` code has errors as follows and needs to be resolved.  I will get through the remaining code and see if there are other errors (can commit this file out of the makefile to bypass temporarily).  The type on the passed arguments needs to be checked.

```
gfortran -g -cpp -fno-align-commons -static -fcheck=bounds -fno-automatic -finit-local-zero -fcheck=do,mem,pointer -I/usr/include -c execut.for
execut.for:1434:24:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 1434 |      1               4, divact2, rec12b)
      |                        1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:1518:26:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 1518 |      1                 1, divact1, rec12b)
      |                          1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2087:21:

 1084 |      1                     0, iwx, rec12b)
      |                           2
......
 2087 |      1               o, iwx, rec12b)
      |                     1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2151:28:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 2151 |      1                   2, divchkR, rec12b)
      |                            1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2166:28:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 2166 |      1                   3, divact2, rec12b)
      |                            1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2174:28:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 2174 |      1                   4, divact2, rec12b)
      |                            1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2249:26:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 2249 |      1                 5, divchkR, rec12b)
      |                          1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
execut.for:2306:26:

 1084 |      1                     0, iwx, rec12b)
      |                              2
......
 2306 |      1                 6, SeepT, rec12b)
      |                          1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/INTEGER(4)).
make: *** [makefile:624: execut.o] Error 1
```

**Comment by Rayrbennett** [comment]
To be clear are these are the result of a new compiler?

**Comment by Rayrbennett** [comment]
To be clear Do you want me to resolve these?

**Comment by Rayrbennett** [comment]
Steve, 
I’m committed to make transition as easy as possible.  Just train me on how to respond to the notification system & I’ll try & perform.

**Comment by smalers** [comment]
I need to do a bit more cleanup and will then commit the files to the repository so they are visible in GitHub.  I will also commit the makefile, which needs to be merged with work I had done before.  I will also publish the updated developer documentation, which describes how to install the new compiler.  Then Ray will have what he needs to install the updated `gfortran` compiler and reproduce the errors that I am seeing.

I also need to compile with both 32-bit and 64-bit `gfortran` and see if the errors are the same with each.  Both versions of the compiler are installed but need to do a `make clean` to make sure the entire compile uses one or the other for object files and linking.

**Comment by smalers** [comment]
I have finished the initial 16.00.47 code integration.  Compiler errors for 64-bit `gfortran` are attached. I'll work with Ray to resolve.

[compile-output.txt](https://github.com/OpenCDSS/cdss-app-statemod-fortran/files/6128581/compile-output.txt)

**Comment by smalers** [comment]
These issues have been resolved and will be included in the next release.  Close the issue.
