### ISSUE TITLE
Need to remove use if isgi throughout code

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-app-statemod-fortran#37]
The `statem.for` code assigns `isgi`.  This variable was previously used to indicate Silicon Graphics workstations.  This code is obsolete and should be removed throughout.  The `makefile` handles `gfortran` and `linux` versions of routines so there is no need for the variable anymore.

**Comment by smalers** [comment]
I removed `isgi` from code.  This will be in the next release.  Close the issue.

**Comment by Rayrbennett** [comment]
Ok on variable isgi
